install:
- cmd: git submodule update --init --recursive
- cmd: bii-support\appveyor\install\all-headless.bat

build_script:
- cmd: bii-support\windows\build\default.bat

environment:
  BLOCK_NAME: sl_ax_engine
  BII_USER: azriel

  matrix:
  - BUILD_SHARED_LIBS: OFF
  - BUILD_SHARED_LIBS: ON
